CompileFlags:
  Add: [ -Wall, -Wextra, -Werror, -I=/usr/include, -stdlib=libc++]


Diagnostics:
  ClangTidy:
    Add: modernize*

  UnusedIncludes: Strict


InlayHints:
  Designators: Yes
  Enabled: Yes

