live_config_reload = true

[colors.bright]
black = "0x9ea7b3"
blue = "0x91cbff"
cyan = "0x39c5cf"
green = "0x4ae168"
magenta = "0xcb9eff"
red = "0xffb1af"
white = "0xd9dee3"
yellow = "0xf7c843"

[colors.cursor]
cursor = "0xf0f3f6"
text = "0x0a0c10"

[colors.normal]
black = "0x7a828e"
blue = "0x71b7ff"
cyan = "0x39c5cf"
green = "0x26cd4d"
magenta = "0xcb9eff"
red = "0xff9492"
white = "0xd9dee3"
yellow = "0xf0b72f"

[colors.primary]
background = "0x0a0c10"
foreground = "0xf0f3f6"


[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"


[window]
decorations = "Full"
opacity = 0.7

[window.padding]
x = 0
y = 0
